version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb 
    ports:
    - 27017:27017
    volumes:
    - /home/user/mongodb/data:/data/db 
  flask-service:
    image: my_flash_image
    restart: always 
    container_name: flash 
    depends_on: mongodb
    ports:
    - 5000:5000
    