global:
  scrape_interval: 15s
  evaluation_interval: 15s 
scrape_configs:  
- job_name: prometheus
  scrape_interval: 10s
  static_configs:
    - targets:
      - localhost:9090
      
- job_name: swarm-services
  scrape_interval: 5s 
  file_sd_configs:
    - files:
      - /etc/prometheus/targets.json
      refresh_interval: 10s